name: Build Workflow

on:
  push:
    branches:
      - main
    paths:
      - '*.py'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v3

      - name: Declare some variables
        shell: bash
        run: |
          echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
          echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> "$GITHUB_ENV"
        
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          architecture: 'x64'
      
      - name: Install requirements
        run: |
          pip install -r requirements.txt
      
      - name: Run PyInstaller
        run: |
          pyinstaller --noconfirm --onedir --console --name "wow_addon_manager"  "main.py"
      
      - name: Copy config files
        run: |
          copy *.json dist\wow_addon_manager
      
      - name: Upload artifacts 
        uses: actions/upload-artifact@v4
        with:
          name: wow_addons_manager
          path: dist/wow_addon_manager
      
      - name: Create tag
        uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: "$(date +'%y%m%d%H%M')"
          tag_exists_error: false
          message: "Latest release"


      - name: Realse  
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "dist/wow_addon_manager"
          commit: ${{ env.sha_short }}
          tag: ${{ github.ref_name }}

